export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const USER_LOGIING = "USER_LOGIING";
export const NETWORK_ERROR = "NETWORK_ERROR";

export const SIGNUP_STARTED = "SIGNUP_STARTED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILLED = "SIGNUP_FAILLED";

export const VERIFICATION_SIGNUP_STARTED = "WEAK_AUTH_VERIFICATION_SIGNUP_STARTED" ;
export const SET_EMAIL_VERIFICATION_STARTED = "WEAK_AUTH_SET_EMAIL_VERIFICATION_STARTED";
export const RESET_PASSWORD_VERIFICATION_STARTED = "WEAK_AUTH_RESET_PASSWORD_VERIFICATION_STARTED";
export const SET_EMAIL_STARTED = "WEAK_AUTH_SET_EMAIL_STARTED";
export const SET_PASSWORD_STARTED = "WEAK_AUTH_SET_PASSWORD_STARTED";
export const RESET_PASSWORD_STARTED = "WEAK_AUTH_RESET_PASSWORD_STARTED";
export const RESEND_TOKEN_FOR_SIGNUP_STARTED ="WEAK_AUTH_RESEND_TOKEN_FOR_SIGNUP_STARTED" ;


export const VERIFICATION_SIGNUP_SUCCESS = "WEAK_AUTH_VERIFICATION_SIGNUP_SUCCESS" ;
export const SET_EMAIL_VERIFICATION_SUCCESS = "WEAK_AUTH_SET_EMAIL_VERIFICATION_SUCCESS";
export const RESET_PASSWORD_VERIFICATION_SUCCESS = "WEAK_AUTH_RESET_PASSWORD_VERIFICATION_SUCCESS";
export const SET_EMAIL_SUCCESS = "WEAK_AUTH_SET_EMAIL_SUCCESS";
export const SET_PASSWORD_SUCCESS = "WEAK_AUTH_SET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "WEAK_AUTH_RESET_PASSWORD_SUCCESS";
export const RESEND_TOKEN_FOR_SIGNUP_SUCCESS ="WEAK_AUTH_RESEND_TOKEN_FOR_SIGNUP_SUCCESS" ;

export const VERIFICATION_SIGNUP_FAILLED = "WEAK_AUTH_VERIFICATION_SIGNUP_FAILLED" ;
export const SET_EMAIL_VERIFICATION_FAILLED = "WEAK_AUTH_SET_EMAIL_VERIFICATION_FAILLED";
export const RESET_PASSWORD_VERIFICATION_FAILLED = "WEAK_AUTH_RESET_PASSWORD_VERIFICATION_FAILLED";
export const SET_EMAIL_FAILLED = "WEAK_AUTH_SET_EMAIL_FAILLED";
export const SET_PASSWORD_FAILLED = "WEAK_AUTH_SET_PASSWORD_FAILLED";
export const RESET_PASSWORD_FAILLED = "WEAK_AUTH_RESET_PASSWORD_FAILLED";
export const RESEND_TOKEN_FOR_SIGNUP_FAILLED ="WEAK_AUTH_RESEND_TOKEN_FOR_SIGNUP_FAILLED" ;



export const RESET = "RESET";