export const NOTIFICATION = "NOTIFICATIONS";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";

export const ALL_COMMUNITY = "ALL_COMMUNITY";
export const MY_COMMUNITY = "MY_COMMUNITY";
export const CREATED_COMMUNITY = "CREATED_COMMUNITY";
export const ADD_ADMIN = "ADD_ADMIN";
export const REMOVE_ADMIN = "REMOVE_ADMIN";
export const ADD_USER = "ADD_USER";
export const SINGLE_COMMUNITY = "SINGLE_COMMUNITY";
export const REMOVE_USER = "REMOVE_USER";

export const PLANETTE_NANCY_PUBLICATIONS = "PLANETTE_NANCY_PUBLICATIONS";
export const NANCY_BOOK_PUBLICATIONS = "NANCY_BOOK_PUBLICATIONS";
export const PUBLICATION = "PUBLICATION";
export const LIKE_PLANETE_PUBLICATION = "LIKE_PLANETE_PUBLICATION";
export const LIKE_PUBLICATION = "LIKE_PUBLICATION";
export const SINGLE_PUBLICATION_INFO = "SINGLE_PUBLICATION_INFO";

export const USER_INFO = "USER_INFO";
export const UPDATE_MY_INFO = "UPDATE_MY_INFO";
export const ABONNEMENTS = "ABONNEMENT";
export const ABONNES = "ABONNES";
export const USER_ABONNES = "USER_ABONNES";
export const FIND_USERS = "FIND_USERS";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_EMAIL_CONFIRM = "CHANGE_EMAIL_CONFIRM";
export const PASSWORD_OPERATION = "PASSWORD_OPERATION";


export const TODOS = "TODOS";
