export default data=[
    {
        id: 1,
        name:'infos Cameroun',
        Nbre_Membre: '45',
        image: require('../../IMG/7.jpg'),
    },
    {
        id: 2,
        name:'clubs des informaticiens',
        Nbre_Membre:'98',
        image: require('../../IMG/8.jpg'),
    },
    {
        id: 3,
        name:'Débats politique',
        Nbre_Membre: '45',
        image: require('../../IMG/9.jpg'),
    },
    {
        id: 4,
        name:'Sports',
        Nbre_Membre: '45',
        image: require('../../IMG/10.jpg'),
    },
    {
        id: 5,
        name:'FC Barcelona fan club',
        Nbre_Membre: '45',
        image: require('../../IMG/11.jpg'),
    },
    {
        id: 6,
        name:'Autour de la Musique',
        Nbre_Membre: '45',
        image: require('../../IMG/12.jpg'),
    },
    {
        id: 7,
        name:'Cinema',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 8,
        name:'Réseau du Free',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 9,
        name:"Entretien d'embauche et vie professionnelle",
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 10,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 11,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 12,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 13,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 14,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 16,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 17,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 18,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 19,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 20,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 21,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 22,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 23,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 24,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 25,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 26,
        name:'infos Cameroun',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 27,
        name:'clubs des informaticiens',
        Nbre_Membre:'98',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 28,
        name:'Débats politique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 29,
        name:'Sports',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 30,
        name:'FC Barcelona fan club',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 31,
        name:'Autour de la Musique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 32,
        name:'Cinema',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 33,
        name:'Réseau du Free',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 34,
        name:"Entretien d'embauche et vie professionnelle",
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 35,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 36,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 37,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 38,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 39,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 40,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 41,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 42,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 43,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 44,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 45,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 46,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 47,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 48,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 49,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 50,
        name:'infos Cameroun',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 51,
        name:'clubs des informaticiens',
        Nbre_Membre:'98',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 53,
        name:'Débats politique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 54,
        name:'Sports',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 55,
        name:'FC Barcelona fan club',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 56,
        name:'Autour de la Musique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 57,
        name:'Cinema',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 58,
        name:'Réseau du Free',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id:59,
        name:"Entretien d'embauche et vie professionnelle",
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 60,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 61,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 62,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 13,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 64,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 66,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 67,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 68,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 69,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 70,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 71,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 72,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 83,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 84,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 85,
        name:'infos du jour',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 91,
        name:'infos Cameroun',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 92,
        name:'clubs des informaticiens',
        Nbre_Membre:'98',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 93,
        name:'Débats politique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 94,
        name:'Sports',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 95,
        name:'FC Barcelona fan club',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 96,
        name:'Autour de la Musique',
        Nbre_Membre: '45',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 7,
        name:'Cinema',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 98,
        name:'Réseau du Free',
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 99,
        name:"Entretien d'embauche et vie professionnelle",
        Nbre_Membre: '9876',
        image: require('../../IMG/avatar-1.jpg'),
    },
    
]