export default data=[
    {
        id: 1,
        name:'infos Cameroun',
        Nbre_message:'12',
        label:'notification sur la dernier évènement du groupe',
        image: require('../../IMG/1.jpg'),
    },
    {
        id: 2,
        name:'clubs des informaticiens',
        Nbre_message:'17',
        label:'notification sur la dernier évènnement du groupe',
        image: require('../../IMG/2.jpg'),
    },
    {
        id: 3,
        name:'Débats politique',
        Nbre_message:'1',
        label:'notification sur la dernier évènement du groupe',
        image: require('../../IMG/3.jpg'),
    },
    {
        id: 4,
        name:'Sports',
        Nbre_message:'',
        label:'notification sur la dernier évènement du groupe',
        image: require('../../IMG/4.jpg'),
    },
    {
        id: 5,
        name:'FC Barcelona fan club',
        Nbre_message:'8',
        label:'notification sur la dernier évènement du groupe',
        image: require('../../IMG/5.jpg'),
    },
    {
        id: 6,
        name:'Autour de la Musique',
        Nbre_message:'8',
        label:'notification sur la dernier évènement du groupe',
        image: require('../../IMG/1.jpg'),
    },
    {
        id: 7,
        name:'Cinema',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/7.jpg'),
    },
    {
        id: 8,
        name:'Réseau du Free',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/8.jpg'),
    },
    {
        id: 9,
        name:"Entretien d'embauche et vie professionnelle",
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/9.jpg'),
    },
    {
        id: 10,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/10.jpg'),
    },
    /*{
        id: 11,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 12,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 13,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 14,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 16,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 17,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 18,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 19,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 20,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 21,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 22,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 23,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 24,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    },
    {
        id: 25,
        name:'infos du jour',
        Nbre_message:'8',
        label:'notification sur la dernière publication',
        image: require('../../IMG/avatar-1.jpg'),
    }*/
   
]